sudo: required

dist: trusty

language: node_js

node_js:
  - "10"

install:
  - npm install

matrix:
  fast_finish: true
  allow_failures:

branches:
  only:
    - surge
script:
  - npm run deploy:beta

notifications:
  email: false
