sudo: required

dist: trusty

language: node_js

node_js:
  - "10"
install:
  - npm -g install gh-pages
  - npm install
matrix:
  fast_finish: true
  allow_failures:

script:
  - npm run build
  - npm run preDeploy

notifications:
  email: false

deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: flippant-error.surge.sh
  on:
    branch: surge
